
dist: trusty
sudo: false
language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2
  - 7.3
  - 7.4

before_install:
  - travis_retry composer self-update

install:
  - rm composer.lock
  - travis_retry composer -n --prefer-source install

jobs:
    include:
    - stage: Code Quality
      env: STATIC_ANALYSIS
      install: travis_retry composer install --prefer-dist
      script: composer test