columns:
  sku:
    string: ~
  categories:
    list: ~
  enabled:
    boolean: ~
  family:
    string: ~
  parent:
    string: ~
  groups:
    list: ~

rows:
  unflatten:
    separator: '-'
  nullify: ~

index:
  sku:

source:
  attributes:
    file: families
    id: code
    filter:
      - attributes

validations:
  property:
    sku:
      unique:
    parent:
      reference_exist:
        file: product_models
        id: code
    family:
      reference_exist:
        file: families
        id: code
  row:
    attributes:
      akeneo_scope:
        source:
          file: attributes
          id: code
        context:
          - localizable
          - scopable
