encode:
  sku:
    string: ~
  categories:
    list: ~
  enabled:
    boolean: ~
  family:
    string: ~
  parent:
    string: ~
  groups:
    list: ~

#
#list:
#  code: attribute_code_and_types
#  options:
#    source: attribute
#    command: key_value_pair
#    id: code
#    value: type

parse:
  type: csv
  reference: sku
  structure: 'akeneo/product/csv'
#    name: 'akeneo/product/csv'
#    context: $attribute_code_and_types
  format:
    delimiter: ';'
    enclosure: '"'

validations:
  include: 'validation/product.yaml'